### ISSUE TITLE
token's circulating supply

### ISSUE THREAD

**Issue by al-matty** [pcko1/etherscan-python#10]
I didn't see a way to get a token's circulating supply, did I just miss it?

**Comment by pcko1** [comment]
hi @al-matty, that should be `get_total_supply_by_contract_address` ([example](https://github.com/pcko1/etherscan-python/blob/master/logs/standard/get_total_supply_by_contract_address.json)) :)

**Comment by al-matty** [comment]
Wow, thanks for your work. Since I'm new to this, what'd be the best way to dive into the usage of etherscan-python?

**Comment by pcko1** [comment]
hmm I would say you should brainstorm about how a blockchain explorer, such as Etherscan, could be of help to you and what kind of projects you can build based on the data you download from there. Then, you can visit the API and see what types of data are actually available and how you can adjust them to the needs of your project (or maybe how to adjust the project to the types of data that you have access to). Be mindful though, Etherscan allows for 5 queries per second, so try to mindful with your queries otherwise you might end up getting temporarily restricted from accessing it :)

**Comment by al-matty** [comment]
That's perfect, thanks.
